# Generated by Django 5.2.14 on 2026-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
            ],
            options={
                "db_table": "aircraft",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.CharField(blank=True, max_length=5, null=True)),
                ("booking_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "bookings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Flights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10, unique=True)),
                ("destination", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
            ],
            options={
                "db_table": "flights",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Passengers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("passport_number", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "passengers",
                "managed": False,
            },
        ),
    ]
