# Generated by Django 5.2.14 on 2026-06-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_bookingorder_bookingorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bookingorder",
            name="seat_class",
            field=models.CharField(default="Эконом", max_length=20),
        ),
        migrations.AddField(
            model_name="bookingorder",
            name="seat_number",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="seat_class",
            field=models.CharField(default="Эконом", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="seat_number",
            field=models.CharField(default="", max_length=5),
        ),
    ]
