# Generated by Django 5.2.14 on 2026-06-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_bookingorder_price_bookingorder_seat_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bookingorderitem",
            name="seat_class",
            field=models.CharField(default="Эконом", max_length=20),
        ),
        migrations.AddField(
            model_name="bookingorderitem",
            name="seat_number",
            field=models.CharField(default="", max_length=5),
        ),
    ]
